//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chef
    {
        public string NomChef { get; set; }
        public string PrenomChef { get; set; }
        public System.DateTime DateNaissanceChef { get; set; }
        public string Tel { get; set; }
        public int IDService { get; set; }
        public string NomUtilisateur { get; set; }
        public string Mdp { get; set; }
        public string Photo { get; set; }
        public string CIN { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
