//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conge
    {
        public int IDConge { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public System.DateTime DateDemandeConge { get; set; }
        public string IDEmp { get; set; }
        public string Etat { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
