//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.Conge = new HashSet<Conge>();
        }
    
        public string NomEmp { get; set; }
        public string PrenomEmp { get; set; }
        public System.DateTime DateNaissanceEmp { get; set; }
        public string TelEmp { get; set; }
        public int IDService { get; set; }
        public string Mdp { get; set; }
        public string NomUtilisateur { get; set; }
        public string Photo { get; set; }
        public string CIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conge> Conge { get; set; }
        public virtual Service Service { get; set; }
    }
}
